version: "2"
services:
  app:
    container_name: covid19
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
        - 3000:3000
    volumes:
        - .:/app
        - node_modules:/app/node_modules
    restart: always
    shm_size: 1g
    logging:
        driver: "json-file"
        options:
            max-size: "8M"
            max-file: "5"
    # command: sh -c "yarn build && yarn start"
    command: yarn start
volumes:
  node_modules: {}
