name: Aomori Opendata Get

on: pull

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node }}

      - name: covid19_aomori_opendata_get Checkout
        uses: actions/checkout@v2.0.0
        with:
          repository: ishi/covid19_aomori_opendata_get
        run: npm install

      - name: csv get
        run: node csv_get.js
        
      - name: csv_to_json.js
        run: |
          node csv_get.js
          mv ./json ../
        
      - name: covid19 checkout
        uses: actions/checkout@v2.0.0
        with:
          repository: CodeForAomori/covid19
          ref: aomori_production

      - name: update json
        run: |
          cp ../*.json data/
            
      - name: git commit
          git config --global user.email "ishi720@gmail.com"
          git config --global user.name "ishi720"
          git status
          git add --all
          git commit -m "[Bot] GitHub Actions - auto run"
          git status
