name: Aomori Opendata Get

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node }}

      - name: covid19_aomori_opendata_get Checkout
        uses: actions/checkout@v2.0.0
        with:
          repository: ishi720/covid19_aomori_opendata_get
      
      - name: npm setup
        run: npm install

      - name: csv get
        run: |
          node csv_get.js
          ls -la csv
        
      - name: csv_to_json.js
        run: |
          node csv_to_json.js
          ls -la json
          
      - name: sickbeds_summary_json_create.json
        run: |
          node sickbeds_summary_json_create.js
          ls -la json

      - name: mv json
        run: |
          mv ./json/*.json ../
          ls -la ../
        
      - name: covid19 checkout
        uses: actions/checkout@v2.0.0
        with:
          repository: CodeForAomori/covid19
          ref: aomori_production

      - name: update json
        run: |
          cp ../*.json data/
            
      - name: git commit
        run: |
          git config --global user.email "ishizuka720@gmail.com"
          git config --global user.name "ishi720"
          git status
          git add --all
          git commit -m "[Bot] GitHub Actions - Data auto update" || true
          git status
          
      - name: git push
        uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: $\{{ secrets.GITHUB_TOKEN }}
          repository: CodeForAomori/covid19
          branch: aomori_production
